export const PACE_STATES = Object.freeze([
  "flow",
  "pressure",
  "danger",
  "recovery",
  "clutch",
  "repair",
]);

export const TEMPO_STATES = Object.freeze([
  "cold",
  "warming",
  "tempo",
  "flow",
  "dominating",
]);

export const PACE_POLICIES = Object.freeze({
  flow: Object.freeze({
    damageMultiplier: 1.0,
    rewardMultiplier: 1.0,
    shieldGainMultiplier: 1.0,
    tempoGainMultiplier: 1.0,
    telegraphTone: "calm",
    injectRecoveryQuestion: false,
    preferKnownMistake: false,
    preferContrastCase: false,
    preferAnalogyResurface: false,
    lessonMode: "tempo",
  }),
  pressure: Object.freeze({
    damageMultiplier: 1.08,
    rewardMultiplier: 1.05,
    shieldGainMultiplier: 1.05,
    tempoGainMultiplier: 1.05,
    telegraphTone: "active",
    injectRecoveryQuestion: false,
    preferKnownMistake: false,
    preferContrastCase: true,
    preferAnalogyResurface: false,
    lessonMode: "contrast",
  }),
  danger: Object.freeze({
    damageMultiplier: 1.18,
    rewardMultiplier: 1.12,
    shieldGainMultiplier: 1.1,
    tempoGainMultiplier: 1.1,
    telegraphTone: "sharp",
    injectRecoveryQuestion: true,
    preferKnownMistake: true,
    preferContrastCase: true,
    preferAnalogyResurface: true,
    lessonMode: "anti_trap",
  }),
  recovery: Object.freeze({
    damageMultiplier: 0.82,
    rewardMultiplier: 1.0,
    shieldGainMultiplier: 1.2,
    tempoGainMultiplier: 1.05,
    telegraphTone: "soft",
    injectRecoveryQuestion: true,
    preferKnownMistake: true,
    preferContrastCase: true,
    preferAnalogyResurface: true,
    lessonMode: "repair",
  }),
  clutch: Object.freeze({
    damageMultiplier: 1.28,
    rewardMultiplier: 1.2,
    shieldGainMultiplier: 0.95,
    tempoGainMultiplier: 1.15,
    telegraphTone: "focused",
    injectRecoveryQuestion: false,
    preferKnownMistake: false,
    preferContrastCase: false,
    preferAnalogyResurface: false,
    lessonMode: "revenge",
  }),
  repair: Object.freeze({
    damageMultiplier: 0.68,
    rewardMultiplier: 0.92,
    shieldGainMultiplier: 1.25,
    tempoGainMultiplier: 0.9,
    telegraphTone: "gentle",
    injectRecoveryQuestion: true,
    preferKnownMistake: true,
    preferContrastCase: true,
    preferAnalogyResurface: true,
    lessonMode: "repair",
  }),
});

export const TEMPO_TIERS = Object.freeze([
  Object.freeze({
    name: "cold",
    minCombo: 0,
    rewardMultiplier: 1,
    damageReduction: 0,
    shieldRefund: 0,
  }),
  Object.freeze({
    name: "warming",
    minCombo: 1,
    rewardMultiplier: 1.04,
    damageReduction: 0.03,
    shieldRefund: 1,
  }),
  Object.freeze({
    name: "tempo",
    minCombo: 3,
    rewardMultiplier: 1.1,
    damageReduction: 0.06,
    shieldRefund: 2,
  }),
  Object.freeze({
    name: "flow",
    minCombo: 5,
    rewardMultiplier: 1.18,
    damageReduction: 0.1,
    shieldRefund: 3,
  }),
  Object.freeze({
    name: "dominating",
    minCombo: 8,
    rewardMultiplier: 1.3,
    damageReduction: 0.14,
    shieldRefund: 4,
  }),
]);
