export const BOSS_PHASE_PLAN = [
  {
    name: "opening pressure",
    turns: 2,
    damageMultiplier: 1.0,
    rewardBonus: 0,
    transitionReward: 4,
    shieldPierce: 0,
    tempoDrain: 0,
    revengeBonus: 2,
    shieldRestore: 0,
  },
  {
    name: "midgame pressure",
    turns: 2,
    damageMultiplier: 1.2,
    rewardBonus: 2,
    transitionReward: 6,
    shieldPierce: 1,
    tempoDrain: 1,
    revengeBonus: 4,
    shieldRestore: 1,
  },
  {
    name: "final push",
    turns: 2,
    damageMultiplier: 1.5,
    rewardBonus: 4,
    transitionReward: 10,
    shieldPierce: 2,
    tempoDrain: 2,
    revengeBonus: 6,
    shieldRestore: 2,
  },
];

function lesson({
  conceptTitle,
  correctAnswer,
  temptingAnswer,
  trapLabel,
  analogyTitle,
  nodeTitle,
}) {
  return {
    conceptTitle,
    correctAnswer,
    temptingAnswer,
    trapLabel,
    analogyTitle,
    nodeTitle,
  };
}

export const NONLINEAR_DAMAGE_CASES = {
  highHp: {
    kind: "encounter",
    maxHp: 30,
    hp: 30,
    shield: 0,
    armor: 4,
    maxShield: 0,
    maxArmor: 6,
    retriesAllowed: 0,
    bossPhasePlan: BOSS_PHASE_PLAN,
  },
  lowHp: {
    kind: "encounter",
    maxHp: 30,
    hp: 8,
    shield: 0,
    armor: 4,
    maxShield: 0,
    maxArmor: 6,
    retriesAllowed: 0,
    bossPhasePlan: BOSS_PHASE_PLAN,
  },
  tempoBoss: {
    kind: "boss",
    maxHp: 24,
    hp: 24,
    shield: 6,
    armor: 3,
    maxShield: 10,
    maxArmor: 6,
    retriesAllowed: 0,
    bossPhasePlan: BOSS_PHASE_PLAN,
  },
};

export const COMBAT_PACING_RUN = {
  encounter: {
    kind: "boss",
    maxHp: 12,
    hp: 12,
    shield: 2,
    armor: 0,
    maxShield: 8,
    maxArmor: 4,
    retriesAllowed: 1,
    bossPhasePlan: BOSS_PHASE_PLAN,
  },
  attempts: [
    {
      questionId: "q-1",
      telegraph: "light",
      correct: true,
      correctAnswer: "yield to the sign",
      temptingAnswer: "go first",
      conceptTitle: "Sign authority",
      trapLabel: "obvious priority",
      analogyTitle: "traffic cop",
      nodeTitle: "Crossing Fields",
      lesson: lesson({
        conceptTitle: "Sign authority",
        correctAnswer: "yield to the sign",
        temptingAnswer: "go first",
        trapLabel: "obvious priority",
        analogyTitle: "traffic cop",
        nodeTitle: "Crossing Fields",
      }),
    },
    {
      questionId: "q-2",
      telegraph: "trap",
      correct: true,
      correctAnswer: "follow the override",
      temptingAnswer: "follow the obvious rule",
      conceptTitle: "Trap defuse",
      trapLabel: "false obvious",
      analogyTitle: "crossroads drill",
      nodeTitle: "Four-Way Labyrinth",
      lesson: lesson({
        conceptTitle: "Trap defuse",
        correctAnswer: "follow the override",
        temptingAnswer: "follow the obvious rule",
        trapLabel: "false obvious",
        analogyTitle: "crossroads drill",
        nodeTitle: "Four-Way Labyrinth",
      }),
    },
    {
      questionId: "q-3",
      telegraph: "critical",
      correct: false,
      correctAnswer: "check the sign first",
      temptingAnswer: "trust the first car",
      conceptTitle: "Right of way",
      trapLabel: "known ground slip",
      analogyTitle: "guard post",
      nodeTitle: "Crossing Fields",
      lesson: lesson({
        conceptTitle: "Right of way",
        correctAnswer: "check the sign first",
        temptingAnswer: "trust the first car",
        trapLabel: "known ground slip",
        analogyTitle: "guard post",
        nodeTitle: "Crossing Fields",
      }),
    },
    {
      questionId: "q-3",
      telegraph: "critical",
      correct: true,
      correctAnswer: "check the sign first",
      temptingAnswer: "trust the first car",
      conceptTitle: "Right of way",
      trapLabel: "known ground slip",
      analogyTitle: "guard post",
      nodeTitle: "Crossing Fields",
      lesson: lesson({
        conceptTitle: "Right of way",
        correctAnswer: "check the sign first",
        temptingAnswer: "trust the first car",
        trapLabel: "known ground slip",
        analogyTitle: "guard post",
        nodeTitle: "Crossing Fields",
      }),
    },
    {
      questionId: "q-4",
      telegraph: "heavy",
      correct: true,
      correctAnswer: "respect the field marker",
      temptingAnswer: "rush the crossing",
      conceptTitle: "Field marker override",
      trapLabel: "overconfidence",
      analogyTitle: "watchtower",
      nodeTitle: "Crossing Fields",
      lesson: lesson({
        conceptTitle: "Field marker override",
        correctAnswer: "respect the field marker",
        temptingAnswer: "rush the crossing",
        trapLabel: "overconfidence",
        analogyTitle: "watchtower",
        nodeTitle: "Crossing Fields",
      }),
    },
    {
      questionId: "q-5",
      telegraph: "medium",
      correct: true,
      correctAnswer: "use the local rule",
      temptingAnswer: "pick the first visible option",
      conceptTitle: "Local rule",
      trapLabel: "visual decoy",
      analogyTitle: "road map",
      nodeTitle: "Crossing Fields",
      lesson: lesson({
        conceptTitle: "Local rule",
        correctAnswer: "use the local rule",
        temptingAnswer: "pick the first visible option",
        trapLabel: "visual decoy",
        analogyTitle: "road map",
        nodeTitle: "Crossing Fields",
      }),
    },
  ],
};
