export const DEFAULT_ATTACK_LIBRARY = Object.freeze({
  light: Object.freeze({
    telegraph: "light",
    damage: 6,
    reward: 3,
    shieldReward: 1,
    tempoGain: 1,
    parryEligible: false,
    shieldPierce: 0,
  }),
  medium: Object.freeze({
    telegraph: "medium",
    damage: 10,
    reward: 5,
    shieldReward: 1,
    tempoGain: 1,
    parryEligible: false,
    shieldPierce: 0,
  }),
  heavy: Object.freeze({
    telegraph: "heavy",
    damage: 15,
    reward: 8,
    shieldReward: 2,
    tempoGain: 1,
    parryEligible: false,
    shieldPierce: 1,
  }),
  trap: Object.freeze({
    telegraph: "trap",
    damage: 12,
    reward: 6,
    shieldReward: 2,
    tempoGain: 2,
    parryEligible: true,
    trapDefuseBonus: 4,
    shieldPierce: 0,
    lessonTag: "anti-trap",
  }),
  critical: Object.freeze({
    telegraph: "critical",
    damage: 20,
    reward: 10,
    shieldReward: 3,
    tempoGain: 2,
    parryEligible: true,
    trapDefuseBonus: 6,
    shieldPierce: 2,
    revengeBonus: 8,
    lessonTag: "contrast",
  }),
});

export const DEFAULT_TEMPO_TIERS = Object.freeze([
  Object.freeze({
    name: "cold",
    minCombo: 0,
    rewardMultiplier: 1,
    damageReduction: 0,
    shieldRefund: 0,
  }),
  Object.freeze({
    name: "warming",
    minCombo: 1,
    rewardMultiplier: 1.04,
    damageReduction: 0.03,
    shieldRefund: 1,
  }),
  Object.freeze({
    name: "tempo",
    minCombo: 3,
    rewardMultiplier: 1.1,
    damageReduction: 0.06,
    shieldRefund: 2,
  }),
  Object.freeze({
    name: "flow",
    minCombo: 5,
    rewardMultiplier: 1.18,
    damageReduction: 0.1,
    shieldRefund: 3,
  }),
  Object.freeze({
    name: "dominating",
    minCombo: 8,
    rewardMultiplier: 1.3,
    damageReduction: 0.14,
    shieldRefund: 4,
  }),
]);

export const DEFAULT_BOSS_PHASE_PLAN = Object.freeze([
  Object.freeze({
    name: "opening pressure",
    turns: 2,
    damageMultiplier: 1.0,
    rewardBonus: 0,
    transitionReward: 4,
    shieldPierce: 0,
    tempoDrain: 0,
    revengeBonus: 2,
    shieldRestore: 0,
  }),
  Object.freeze({
    name: "midgame pressure",
    turns: 2,
    damageMultiplier: 1.2,
    rewardBonus: 2,
    transitionReward: 6,
    shieldPierce: 1,
    tempoDrain: 1,
    revengeBonus: 4,
    shieldRestore: 1,
  }),
  Object.freeze({
    name: "final push",
    turns: 2,
    damageMultiplier: 1.45,
    rewardBonus: 4,
    transitionReward: 10,
    shieldPierce: 2,
    tempoDrain: 2,
    revengeBonus: 6,
    shieldRestore: 2,
  }),
]);

export const DEFAULT_DEFENSE_PROFILE = Object.freeze({
  maxShield: 24,
  maxArmor: 8,
  lowHpAmplifier: 0.35,
  armorMitigationPerPoint: 0.035,
  shieldRestoreOnRetryRatio: 0.4,
  armorRestoreOnRetryRatio: 0.25,
  revengeShieldRefund: 5,
});

export const DEFAULT_RETRY_PROFILE = Object.freeze({
  retriesAllowed: 1,
  revengeTurns: 2,
  revengeRewardBonus: 8,
  revengeShieldRefund: 5,
  minimalRetryShield: 4,
  minimalRetryArmor: 1,
  checkpointShieldFraction: 0.5,
  checkpointArmorFraction: 0.5,
});
