import { attachDefaultEdgeWeights, buildMapIndex } from "./graph.mjs";

export const chapter1Concepts = [
  { id: "initiative-order", title: "Who Goes First", cluster: "initiative" },
  { id: "priority-basics", title: "Priority Basics", cluster: "initiative" },
  { id: "default-yield", title: "Default Yield", cluster: "initiative" },
  { id: "stop-command", title: "Stop Command", cluster: "authority" },
  { id: "yield-command", title: "Yield Command", cluster: "authority" },
  { id: "signal-hierarchy", title: "Signal Hierarchy", cluster: "authority" },
  { id: "temporary-override", title: "Temporary Override", cluster: "authority" },
  { id: "sign-overrides-intuition", title: "Sign Over Intuition", cluster: "authority" },
  { id: "general-vs-local", title: "General vs Local", cluster: "exceptions" },
  { id: "conflict-resolution", title: "Conflict Resolution", cluster: "exceptions" },
  { id: "exception-context", title: "Exception Context", cluster: "exceptions" },
  { id: "override-logic", title: "Override Logic", cluster: "exceptions" },
  { id: "scene-scan", title: "Scene Scan", cluster: "perception" },
  { id: "relevant-signal", title: "Relevant Signal", cluster: "perception" },
  { id: "ignore-distractors", title: "Ignore Distractors", cluster: "perception" },
  { id: "parse-under-pressure", title: "Parse Under Pressure", cluster: "perception" },
  { id: "false-obvious", title: "False Obvious", cluster: "traps" },
  { id: "tiny-override", title: "Tiny Override", cluster: "traps" },
  { id: "last-word-trap", title: "Last-Word Trap", cluster: "traps" },
  { id: "signal-betrayal", title: "Signal Betrayal", cluster: "traps" },
  { id: "visual-decoy", title: "Visual Decoy", cluster: "traps" },
  { id: "four-way-stop-order", title: "Four-Way Stop Order", cluster: "labyrinth" },
  { id: "conflicting-vehicle-order", title: "Conflicting Vehicle Order", cluster: "labyrinth" },
  { id: "right-before-left", title: "Right Before Left", cluster: "labyrinth" },
];

export const chapter1TrapPatterns = [
  { id: "false_obvious", title: "False Obvious" },
  { id: "tiny_override", title: "Tiny Override" },
  { id: "last_word_trap", title: "Last-Word Trap" },
  { id: "signal_betrayal", title: "Signal Betrayal" },
  { id: "corridor_theft", title: "Corridor Theft" },
  { id: "rule_collapse", title: "Rule Collapse" },
  { id: "exception_ambush", title: "Exception Ambush" },
  { id: "premature_certainty", title: "Premature Certainty" },
  { id: "visual_decoy", title: "Visual Decoy" },
  { id: "known_ground_slip", title: "Known Ground Slip" },
];

const chapter1RegionInfo = {
  id: "crossing_fields",
  title: "Crossing Fields",
  theme: {
    visual: "open plains, crossroads, signposts, long sightlines",
    audio: "disciplined, forward-driving, ceremonial",
    narrativeRole: "first major threshold",
  },
};

const mainNodeBlueprints = [
  {
    id: "crossing-fields-gate",
    type: "region",
    title: "Crossing Fields",
    position: { x: 0, y: 0 },
    scopeId: "crossing_fields",
    regionId: "crossing_fields",
    tags: ["entry", "region"],
    flavor: "The road is a system, not random facts.",
  },
  {
    id: "initiative-ridge",
    type: "concept",
    title: "Initiative Ridge",
    position: { x: 1, y: -1 },
    scopeId: "crossing_fields",
    regionId: "crossing_fields",
    conceptIds: ["initiative-order", "priority-basics", "default-yield"],
    tags: ["initiative", "priority"],
  },
  {
    id: "signal-command-post",
    type: "concept",
    title: "Signal Command Post",
    position: { x: 2, y: -1 },
    scopeId: "crossing_fields",
    regionId: "crossing_fields",
    conceptIds: [
      "stop-command",
      "yield-command",
      "signal-hierarchy",
      "temporary-override",
      "sign-overrides-intuition",
    ],
    tags: ["signals", "authority"],
  },
  {
    id: "exception-bastion",
    type: "concept",
    title: "Exception Bastion",
    position: { x: 3, y: 0 },
    scopeId: "crossing_fields",
    regionId: "crossing_fields",
    conceptIds: [
      "general-vs-local",
      "conflict-resolution",
      "exception-context",
      "override-logic",
    ],
    tags: ["exceptions", "rules"],
  },
  {
    id: "observer-post",
    type: "concept",
    title: "Observer Post",
    position: { x: 2, y: 1 },
    scopeId: "crossing_fields",
    regionId: "crossing_fields",
    conceptIds: ["scene-scan", "relevant-signal", "ignore-distractors", "parse-under-pressure"],
    tags: ["perception", "focus"],
  },
  {
    id: "trap-archive",
    type: "trap",
    title: "Trap Archive",
    position: { x: 1, y: 1 },
    scopeId: "crossing_fields",
    regionId: "crossing_fields",
    trapPatternIds: [
      "false_obvious",
      "tiny_override",
      "last_word_trap",
      "signal_betrayal",
      "visual_decoy",
    ],
    tags: ["trap-literacy", "warning"],
  },
  {
    id: "four-way-labyrinth-gate",
    type: "submap",
    title: "The Four-Way Labyrinth",
    position: { x: 4, y: 0 },
    scopeId: "crossing_fields",
    regionId: "crossing_fields",
    submapId: "four_way_labyrinth",
    opensSubmapId: "four_way_labyrinth",
    tags: ["submap", "recursive-map"],
    flavor: "A place where naive intuition fails hard.",
  },
  {
    id: "right-of-way-beast",
    type: "boss",
    title: "The Right-of-Way Beast",
    position: { x: 5, y: 0 },
    scopeId: "crossing_fields",
    regionId: "crossing_fields",
    bossId: "right_of_way_beast",
    tags: ["boss", "guardian"],
    flavor: "The first true guardian of lawful motion.",
  },
];

const labyrinthNodeBlueprints = [
  {
    id: "labyrinth-entry",
    type: "concept",
    title: "Labyrinth Entry",
    position: { x: 0, y: 0 },
    scopeId: "four_way_labyrinth",
    regionId: "crossing_fields",
    submapId: "four_way_labyrinth",
    conceptIds: ["four-way-stop-order", "conflicting-vehicle-order"],
    tags: ["submap-entry", "order"],
  },
  {
    id: "labyrinth-priority-crossing",
    type: "concept",
    title: "Priority Crossing",
    position: { x: 1, y: -1 },
    scopeId: "four_way_labyrinth",
    regionId: "crossing_fields",
    submapId: "four_way_labyrinth",
    conceptIds: ["right-before-left", "priority-basics", "initiative-order"],
    tags: ["priority", "crossing"],
  },
  {
    id: "labyrinth-exception-node",
    type: "concept",
    title: "Exception Node",
    position: { x: 2, y: 0 },
    scopeId: "four_way_labyrinth",
    regionId: "crossing_fields",
    submapId: "four_way_labyrinth",
    conceptIds: ["general-vs-local", "exception-context", "override-logic"],
    tags: ["exceptions", "recursion"],
  },
  {
    id: "labyrinth-signal-overlook",
    type: "concept",
    title: "Signal Overlook",
    position: { x: 1, y: 1 },
    scopeId: "four_way_labyrinth",
    regionId: "crossing_fields",
    submapId: "four_way_labyrinth",
    conceptIds: ["signal-hierarchy", "temporary-override", "sign-overrides-intuition"],
    tags: ["signal", "override"],
  },
  {
    id: "labyrinth-corridor-theft",
    type: "trap",
    title: "Corridor Theft",
    position: { x: 3, y: -1 },
    scopeId: "four_way_labyrinth",
    regionId: "crossing_fields",
    submapId: "four_way_labyrinth",
    trapPatternIds: ["corridor_theft", "rule_collapse"],
    tags: ["trap", "ambush"],
  },
  {
    id: "labyrinth-rule-collapse",
    type: "trap",
    title: "Rule Collapse",
    position: { x: 3, y: 0 },
    scopeId: "four_way_labyrinth",
    regionId: "crossing_fields",
    submapId: "four_way_labyrinth",
    trapPatternIds: ["exception_ambush", "premature_certainty"],
    tags: ["trap", "exceptions"],
  },
  {
    id: "labyrinth-known-ground-slip",
    type: "trap",
    title: "Known Ground Slip",
    position: { x: 3, y: 1 },
    scopeId: "four_way_labyrinth",
    regionId: "crossing_fields",
    submapId: "four_way_labyrinth",
    trapPatternIds: ["known_ground_slip", "false_obvious"],
    tags: ["memory", "reclaim"],
  },
  {
    id: "labyrinth-exit",
    type: "submap",
    title: "Labyrinth Exit",
    position: { x: 4, y: 0 },
    scopeId: "four_way_labyrinth",
    regionId: "crossing_fields",
    submapId: "four_way_labyrinth",
    opensSubmapId: null,
    tags: ["exit", "return"],
  },
];

const chapter1Edges = attachDefaultEdgeWeights([
  { id: "edge-gate-to-initiative", from: "crossing-fields-gate", to: "initiative-ridge", type: "unlocks" },
  { id: "edge-initiative-to-signal", from: "initiative-ridge", to: "signal-command-post", type: "prerequisite" },
  { id: "edge-signal-to-exception", from: "signal-command-post", to: "exception-bastion", type: "prerequisite" },
  { id: "edge-exception-to-observer", from: "exception-bastion", to: "observer-post", type: "prerequisite" },
  { id: "edge-observer-to-traps", from: "observer-post", to: "trap-archive", type: "confusion" },
  { id: "edge-traps-to-labyrinth", from: "trap-archive", to: "four-way-labyrinth-gate", type: "unlocks" },
  { id: "edge-labyrinth-to-boss", from: "four-way-labyrinth-gate", to: "right-of-way-beast", type: "unlocks" },
]);

const chapter1SubmapEdges = attachDefaultEdgeWeights([
  { id: "lab-edge-entry-to-priority", from: "labyrinth-entry", to: "labyrinth-priority-crossing", type: "prerequisite" },
  { id: "lab-edge-priority-to-exception", from: "labyrinth-priority-crossing", to: "labyrinth-exception-node", type: "prerequisite" },
  { id: "lab-edge-exception-to-signal", from: "labyrinth-exception-node", to: "labyrinth-signal-overlook", type: "prerequisite" },
  { id: "lab-edge-signal-to-theft", from: "labyrinth-signal-overlook", to: "labyrinth-corridor-theft", type: "confusion" },
  { id: "lab-edge-theft-to-collapse", from: "labyrinth-corridor-theft", to: "labyrinth-rule-collapse", type: "confusion" },
  { id: "lab-edge-collapse-to-slip", from: "labyrinth-rule-collapse", to: "labyrinth-known-ground-slip", type: "confusion" },
  { id: "lab-edge-slip-to-exit", from: "labyrinth-known-ground-slip", to: "labyrinth-exit", type: "unlocks" },
]);

export const chapter1MapDefinition = {
  region: chapter1RegionInfo,
  entryNodeId: "crossing-fields-gate",
  bossNodeId: "right-of-way-beast",
  nodes: mainNodeBlueprints,
  edges: chapter1Edges,
  submaps: [
    {
      id: "four_way_labyrinth",
      title: "The Four-Way Labyrinth",
      parentRegionId: "crossing_fields",
      entryNodeId: "labyrinth-entry",
      recursive: true,
      purpose: "Prove recursive map design and known-ground replay.",
      nodes: labyrinthNodeBlueprints,
      edges: chapter1SubmapEdges,
    },
  ],
  recommendedRoutes: {
    main: [
      "crossing-fields-gate",
      "initiative-ridge",
      "signal-command-post",
      "exception-bastion",
      "observer-post",
      "trap-archive",
      "four-way-labyrinth-gate",
      "right-of-way-beast",
    ],
    submap: [
      "labyrinth-entry",
      "labyrinth-priority-crossing",
      "labyrinth-exception-node",
      "labyrinth-signal-overlook",
      "labyrinth-corridor-theft",
      "labyrinth-rule-collapse",
      "labyrinth-known-ground-slip",
      "labyrinth-exit",
    ],
  },
  conceptCatalog: chapter1Concepts,
  trapPatterns: chapter1TrapPatterns,
};

export const chapter1MapIndex = buildMapIndex(chapter1MapDefinition);

export const chapter1RegionCard = {
  ...chapter1RegionInfo,
  submapId: "four_way_labyrinth",
  bossId: "right_of_way_beast",
  conceptCount: chapter1Concepts.length,
  trapPatternCount: chapter1TrapPatterns.length,
};

export const chapter1ScopeOrder = ["crossing_fields", "four_way_labyrinth"];
